name: integration-test-latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: MINETEST_VERSION=latest ./integration-test.sh
